# Generated by Django 3.2.25 on 2025-08-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_satff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nmae',
            new_name='name',
        ),
    ]
